### ISSUE TITLE
Work well on mac, but fail compiling in Raspberry Pi 4

### ISSUE THREAD

**Issue by xoco70** [matcornic/addic7ed#3]
Here is the log when compiling, it seems go-textdistance is not working
```
pi@raspberrypi:~/go/src/github.com/addic7ed $ go build
# github.com/masatana/go-textdistance
../../../pkg/mod/github.com/masatana/go-textdistance@v0.0.0-20171214133840-59954f2a9d67/util.go:7:12: constant 9223372036854775807 overflows int
```

**Comment by matcornic** [comment]
Probably due to issue, fixed by @masatana here https://github.com/masatana/go-textdistance/commit/e12484616aa122097708a9dd2ed83be81f4346f4

New version of this library (/!\ which now uses Go 1.13 and modules) should not have this issue anymore.
