### ISSUE TITLE
Didn't work with when multiple results

### ISSUE THREAD

**Issue by xoco70** [matcornic/addic7ed#4]
Hi, 

I have tested it with file: 

Borgia S01E01 BD Rip 720p Compact HEVC 10 Bit AAC Stereo EN SRT

When I put on search page in Addicted, I get 2 results, but when the code search for inexistant  .titulo class, so it doesnt find any result.

Analysing Addicted search page, result is: 

```
<table class="tabel" align="center" width="80%" border="0">

<tr>
  <td>
    <img src="https://www.addic7ed.com/images/television.png" /></td>
    <td><a href="serie/Borgia/1/1/1492" debug="52384">Borgia - 01x01 - 1492</a></td>
</tr>
<tr>
<tr>
<td><img src="https://www.addic7ed.com/images/television.png" /></td>
<td>
  <a href="serie/The_Borgias/1/1/The_Poisoned_Chalice" debug="41974">The Borgias - 01x01 - The Poisoned Chalice</a>
</td>
</tr>
<tr>
<p>
<p>
 </table>
```

Add7cted has bad HTML code :(

**Comment by matcornic** [comment]
Should be fixed now. It was not because of Addi7ed HTML (this library was supposed to handle the case of a show getting two or more results).

It was because the show name was not passed encoded to the URL (so there was a misinterpretation of some chars in your filename).

**Comment by matcornic** [comment]
https://github.com/matcornic/addic7ed/commit/2b5ed3d93c33869eb30509abaa94cdb5f40159be#diff-8795a6cb91b3afefa165851f9f088db3R115
